### ISSUE TITLE
releases download???

### ISSUE THREAD

**Issue by dewiweb** [ebu/ear-production-suite#1]
Where can I download ear-production-suite? Links on website are dead...
Do you plan to release for linux ?
Regards,
dewiweb

**Comment by kickermeister** [comment]
Hi deriweb, 

Thanks for your message. We only published the binaries and the source code of the EAR Production Suite today, so you couldn't find them until now. You can download them for macOS and Windows from https://github.com/ebu/ear-production-suite/releases . We currently don't have plans to support Linux releases and I don't know how much work it would be to build the binaries for it. Do you think that would be possible, @rsjtaylor ?

**Comment by rsjtaylor** [comment]
Hi @dewiweb, I think we had an earlier iteration of the reaper extension *building* on Linux, although I don't think we ever tested whether or not it actually worked. I've no idea what the situation is with VST3 on Linux so the plugins may be more challenging. I'm planning to spend some time improving CI in the next week or so and a gcc workflow would be helpful just from the point of view of catching additional warnings, so I'll attempt to produce a linux build while I'm doing that. As @kickermeister said it's not really something we planned to support, so if it turns out to be non trivial we might have to leave it. Pull requests are very welcome however :)

**Comment by dewiweb** [comment]
Hi @rsjtaylor ,
Apparently no news about a possible linux release or instructions to compile for it? ;)

**Comment by rsjtaylor** [comment]
Hi, apologies - I did give this a go when messing about with CI but forgot to update this issue.
Unfortunately, the major version of JUCE we build the plugins against doesn't have support for VST3 on linux. The latest JUCE does, however we've no plans to update in the near future so probably no linux release any time soon.
