### ISSUE TITLE
ADM import refused due to AudioTrackFormatID issue in chna

### ISSUE THREAD

**Issue by WernerBleisteiner** [ebu/ear-production-suite#146]
I know about incompatibilities with non EPS created ADM.
This ones come from a simple MHAS 3.6 created ADM with just a 4+7+0 channel-bed plus a rotating single object in 3 "presets" (as audioProgrammes are called in MPEG-H).
The thing here seems to be related to a different description of the AudioTrackFormatID in the chna between BS.2076-1 and BS.2076-2.
The supposed relevant paragraphs of both docs are attached as screenshot.
AFAIK EPS until now is based on 2076-1, whereas MPEG-H ADM profiles refer to 2076-2, right?
Don't know anything else about the issue.
Any solution foreseeable?

![image](https://user-images.githubusercontent.com/22868982/140790920-33f5f220-eaa4-4037-9221-850586e8d551.jpeg)
![image](https://user-images.githubusercontent.com/22868982/140790339-bf8751dd-8710-42d5-b3f3-f5a7859a4c4d.jpeg)

**Comment by firthm01** [comment]
Hi Werner,
You're correct in that this is a feature of 2076-2 that is not supported in 2076-1, which the EPS is based upon. However, the underlying issue is slightly different: (my best guess without seeing the ADM metadata of the file...)
2076-2 allows TrackFormat and StreamFormat elements to be omitted where PCM audio is used as they become largely redundant. In this case, the ChannelFormat ID is used in the "TrackFormatID" field of a CHNA chunk entry. The EPS, being based on 2076-1, expects only to find a TrackFormat ID in this field and so complains when the ID it finds is not a valid TrackFormat ID.
I suspect the fix may be quite simple, but I will have to investigate further as it may have further knock-on effects. Hopefully we can get a fix together quickly.

**Comment by WernerBleisteiner** [comment]
Hi Matt,
thanks for your explanation. I'll attach the axml of the original ADM (created with MHAS 3.7 that's based upon BS.2076-2) along with manually fixed version to bypass the first issue (deleting the "S48000" entries for time code) plus the chna.
Reworking the axml is easy using ear-utils. However, I guess, any manipulation of the chna would have to be made with a HexEditor, right?
Maybe this helps to identify the issue.
It's not urgent so solve this - just another 'observation'.
If you are to shift EPS to BS.2076-2 anyway, that'd be fine. 
I'm presently still running on 'build 264'.
[MHAPI-CHANNEL-ID 4-7-0-SEQUENCE-v3.0-ADM.wav-adm-chna-axml-ISSUE.zip](https://github.com/ebu/ear-production-suite/files/7545950/MHAPI-CHANNEL-ID.4-7-0-SEQUENCE-v3.0-ADM.wav-adm-chna-axml-ISSUE.zip)

**Comment by rsjtaylor** [comment]
Thanks for this - I think the issues with the 2076-2 time format and chna chunk should now be resolved in the 2076-2 branch (see #151), however the file will still not import cleanly as I believe it uses a custom pack format for the bed (CICP 19?) - EPS currently only supports importing directspeakers pack formats that are specified in the common definitions, so that object winds up imported as a track with the correct audio but no metadata plugin.

**Comment by firthm01** [comment]
Closing - 2076-2 support added for CHNA and timestamps in 0.7.0. Remaining issue (non-common-def packformat) is out of scope.
