### ISSUE TITLE
Reaper crashes when trying to add EAR Binaural Monitor Plugin

### ISSUE THREAD

**Issue by WernerBleisteiner** [ebu/ear-production-suite#176]
When trying to add or replace an existing monitor track with the EAR Binaural Monitor plugin to the provided EPS template session, Reaper crashes immediately.
This does not occur with a blank Reaper session with only one new track and the EAR Binaural plugin.
More tests not yet made.
Had previously EPS 0.6.0 and since September 21 an artefact (build #264) installed and now replaced all plugins with the new 0.7.0 beta from the website.
Report attached.
Machine: MacBookPro late 2013
Mac OS 10.14.6
Reaper 6.4
[REAPER_2022-02-10-141851_MacBook-Pro-3.crash.zip](https://github.com/ebu/ear-production-suite/files/8041346/REAPER_2022-02-10-141851_MacBook-Pro-3.crash.zip)
6

**Comment by firthm01** [comment]
I know you mentioned you had replaced all the plug-ins, but this might be worth double-checking. Compare the version numbers of the plug-ins in the bottom corner of the GUI (if it's missing then it's definitely a 0.6.0 plug-in). The only reason I mention this is that we had to change the format of the metadata sent between plug-ins since the binaural plug-in required additional information to determine how many channels to reserve. If you're running a mismatch of plug-ins, it might not be receiving this additional information and this is the type of error I would expect to see.

**Comment by WernerBleisteiner** [comment]
OK. Sorry. My fault. 🙄
For whatever reasons there was another previous eps plugin set located in ~/Library/Audio/Plug-Ins/VST3. 
No more crashes after having deleted that one...

**Comment by firthm01** [comment]
No problem - it's a good thing to have pointed out! We should be handling that case more gracefully than just crashing 😃 I'll open another issue

**Comment by firthm01** [comment]
#180
