### ISSUE TITLE
EAR Monitoring 2+7+0

### ISSUE THREAD

**Issue by ravettel** [ebu/ear-production-suite#23]
It's currently not possible to monitor in 7.1.2, which is the most widespread supported configuration by 3rd party plugins.

**Comment by Dniel97** [comment]
Would really appreciate this feature too, the 7.1.2 channel layout is already configured here: https://github.com/ebu/ear-production-suite/blob/081fc5c63295962003839bd5f799e5eadcecd09b/ear-production-suite/lib/include/speaker_setups.hpp#L182 so it should be pretty easy to create the new layout for monitoring in the CMake https://github.com/ebu/ear-production-suite/blob/081fc5c63295962003839bd5f799e5eadcecd09b/ear-production-suite/plugins/monitoring/CMakeLists.txt#L28

**Comment by merktj** [comment]
I've just tried to add the Monitoring together with [adaptions](https://github.com/merktj/ear-production-suite/tree/ial_additional_speaker_setups) in libadm to support additional layouts for #30 . 
However, I get an `ear:unknown_layout` exception when scanning for the VST3 plugin coming from libear's `bs2051.cpp`.
So the issue is that libear only supports layouts specified by BS.2051.

**Comment by Dniel97** [comment]
So you added `add_monitoring_plugin("2+7+0" "7.1.2" "A10")` to the `CMakeList`? And it wasn't able to load the compiled VST3 due to a `ear:unknown_layout`? I tried building it myself but the instructions in the readme are somewhat incomplete so I was able to build it but they didn't work at all.

**Comment by merktj** [comment]
Yes, I did what you described. For me the build instructions worked pretty well, even though it is a bit of effort to correctly configure `vcpkg` for the windows build.
