### ISSUE TITLE
Visible version

### ISSUE THREAD

**Issue by WernerBleisteiner** [ebu/ear-production-suite#6]
Just found out, that there's an update on EPS now. 
Great!
(would have loved to receive a note about that while watching  the early-access git ;) )

What about stating the current version of the plugins correctly in the VSTs?
They're all still at 0.1.0 (see screenshot)
<img width="1154" alt="Bildschirmfoto 2020-09-30 um 12 01 41" src="https://user-images.githubusercontent.com/22868982/94673050-6db9f780-0316-11eb-9463-c67992476708.png">

**Comment by kickermeister** [comment]
Apologies, @WernerBleisteiner for not informing you. We released the public beta under https://github.com/ebu/ear-production-suite two weeks ago during a webinar organized by the EBU. It was also planned to publish a press release alongside but this has not yet happened unfortunately so we are still waiting with social media & blog posts..  There is unfortunately no sensible automatic way to inform all beta-testers about the public release. We should indeed do that manually!

Regarding the version, I have no idea why macOS is displaying the wrong version. The public release should be 0.6.0 now. Perhaps @rsjtaylor has an idea?

**Comment by rsjtaylor** [comment]
I'd expect this to come from [here](https://github.com/ebu/ear-production-suite/blob/26c0aa4230d27c895048d125ca09859c56eba2f5/ear-production-suite/resources/juce/AppConfig.h.in#L384 ) which should be populated from the cmake project version at configure time. That is already set to 0.6.0. 

I think cmake only generates files if they don't already exist in the build directory. As the version bump was one of the last things we did, I suspect that the release might have accidentally been built on macOS with a stale version of this config. 

I'm currently working on automatically packaging from CI to enable binary snapshots of the main branch. If it is a case of stale AppConfig.h headers, that should fix it, if not I'll do some more digging.

**Comment by rsjtaylor** [comment]
TL/DR, should now be fixed, but can't merge yet due to 3rd party problem.

This is with the updated CI build, unfortunately I can't merge those changes yet. The main msys2 package repo went down at the end of last week and have yet to come back. This breaks a lot of vcpkg packages on windows, which in turn breaks our build. Currently builds on main are working as the vcpkg output is cached, but updating the build scripts will invalidate those caches. So once the upstream issue is fixed and the build changes are merged, this issue should go away.
